### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#151]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#3

**In which task and step of the codelab can this issue be found?**
Calculate the tip and round it up

**Describe the problem**
It seems that the following setence should not be put in a code block, but it is:
"For a `Switch` element, you can check the `isChecked` attribute to see if the switch is "on"."

**Steps to reproduce?**
Not applicable.

**Versions**
Not applicable.

**Additional information**
Nil

**Comment by osuleymanova** [comment]
@KKH-tw 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3
