### ISSUE TITLE
Android Basics: polished-user-experience

### ISSUE THREAD

**Issue by vikasz1** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#181]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Data binding is not explained but being used as if user knows already. Go through Codelab no. 3 section 3.
![Screenshot from 2021-07-13 18-26-33](https://user-images.githubusercontent.com/62638545/125455348-33f16458-fbfa-4aae-9fb9-8603417029db.png)

**Comment by aicarambazigalo** [comment]
This([polished user experience](https://developer.android.com/codelabs/basic-android-kotlin-training-polished-user-experience#0)) codelab builds on the [previous ](https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2)codelab(Tip Calculator) in which view binding is explained. That must be why it's assumed known in this codelab since it's a requirement to have Tip Calculator app already, ie. 
```
What you need

    A computer with Android Studio installed.
    Code for the Tip Time app from completing the previous codelabs
```
