### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by Andy-Cuong** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#345]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Step 6, Move vector drawable files into -v26 directory

**Describe the problem**
If the directory is named **drawable-anyapi-v26**, the build will fail with an error of *Invalid resource directory name*
When I rename it to **drawable-v26**, the build is carried out successfully. Therefore the I assume the directory name should be drawable-v26

**Versions**
Android Studio: Chipmunk
Emulator API: API 31

**Additional information**
![image](https://user-images.githubusercontent.com/94699066/169107354-726a2740-e556-414e-9188-1c571038b9f8.png)

![image](https://user-images.githubusercontent.com/94699066/169107942-75aa5cb2-c827-4eb2-b027-cd14c76f72c5.png)

**Comment by osuleymanova** [comment]
@Andy-Cuong 
Thank you for reaching out to us and providing the screenshot of the error. You've got the error message "Invalid resource directory name " because of wrong spelling of the directory name drawable-anyapi-v26. It should be drawable-anydpi-v26:

![Screen Shot 2022-09-14 at 2 34 44 PM](https://user-images.githubusercontent.com/86437155/190267085-84f6db65-d884-4985-ab3c-aba492737143.png)
