### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by uzbeki** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#50]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#6

**In which task and step of the codelab can this issue be found?**
7. Summary

**Describe the problem**
The section that says "Use the super keyword to reference functions and properties in the parent class." is wrong. I did not use super keyword nor am I asked to use it during the Codelab lesson. 

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#6
2. Click on 7.Summary section
3. See error...

**Versions**
_Android Studio version:_ 4.1.1
_API version of the emulator:_ not relevant

**Comment by amindadgar** [comment]
If I understand your question right then my answer would be this
Using The super keyword in an overridden function will call the codes in parent function too ( I named the function in inherited class as parent function). And if you don't use the super keyword then you would ignore the codes in parent function and just your code will run.

For example you have a class like this :
```
open class Property(val name:String) {
    open fun printName(){
        println(name)
    }
}
```
And you will make this two classed to be inherited of your class:

```
class newProperty(val myName: String): Property(myName){
    override fun printName(){
         // here we called the super keyword
        super.printName()
        println("this is my overriden function with super keyword")
    }
}

class newProperty2(val myName: String): Property(myName){
    override fun printName(){
         // here we won't call the super keyword
        println("this is my overriden function without super keyword!")
    }
} 
```
By running this code in your main function
```
fun main(){
   val n = newProperty("Nilson")
   n.printName()
}
```
**The Result For using the super keyword will be:**
   _Nilson
this is my overriden function with super keyword_

And By running This code 
```
fun main(){
   val n = newProperty2("Nilson")
   n.printName()
}
```
**The Result for the function without super keyword will be**
_this is my overriden function without super keyword!_

I've attached some links for you to get a better understanding
1. https://www.journaldev.com/19705/kotlin-inheritance#:~:text=All%20classes%20in%20Kotlin%20have,because%20of%20famous%20diamond%20problem.
2. https://stackoverflow.com/a/46400277

And if you had more questions just ask me 🙂

**Comment by jtavva** [comment]
@amindadgar Thank you so much for replying to the query. 
@uzbeki, Hope that answers your query.

Please reopen the issue if you have further questions.
