### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by dbzix** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#98]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator

**In which task and step of the codelab can this issue be found?**
8. Summary

**Describe the problem**
Incorrect description of property to check in a RadioGroup view

**Steps to reproduce?**
1. Go to https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator
2. Click on 8. Summary
3. See error in text "Use the checkRadioButtonId attribute of a RadioGroup to find which RadioButton is selected", here "checkRadioButtonId" should be replaced with "check**ed**RadioButtonId"

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![calculate the tip text issue](https://user-images.githubusercontent.com/5552696/113394168-6eecdf80-93a0-11eb-92e0-06758660f673.png)

**Comment by osuleymanova** [comment]
@dbzix 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#7
